use crate::ast_to_doc::node::*;
use crate::doc::*;
use ruby_prism::*;

pub fn print(node: &Node) -> Doc {
    match node {
        Node::AliasGlobalVariableNode { .. } => alias_global_variable_node::print(node),
        Node::AliasMethodNode { .. } => alias_method_node::print(node),
        Node::AlternationPatternNode { .. } => alternation_pattern_node::print(node),
        Node::AndNode { .. } => and_node::print(node),
        Node::ArgumentsNode { .. } => arguments_node::print(node),
        Node::ArrayNode { .. } => array_node::print(node),
        Node::ArrayPatternNode { .. } => array_pattern_node::print(node),
        Node::AssocNode { .. } => assoc_node::print(node),
        Node::AssocSplatNode { .. } => assoc_splat_node::print(node),
        Node::BackReferenceReadNode { .. } => back_reference_read_node::print(node),
        Node::BeginNode { .. } => begin_node::print(node),
        Node::BlockArgumentNode { .. } => block_argument_node::print(node),
        Node::BlockLocalVariableNode { .. } => block_local_variable_node::print(node),
        Node::BlockNode { .. } => block_node::print(node),
        Node::BlockParameterNode { .. } => block_parameter_node::print(node),
        Node::BlockParametersNode { .. } => block_parameters_node::print(node),
        Node::BreakNode { .. } => break_node::print(node),
        Node::CallAndWriteNode { .. } => call_and_write_node::print(node),
        Node::CallNode { .. } => call_node::print(node),
        Node::CallOperatorWriteNode { .. } => call_operator_write_node::print(node),
        Node::CallOrWriteNode { .. } => call_or_write_node::print(node),
        Node::CallTargetNode { .. } => call_target_node::print(node),
        Node::CapturePatternNode { .. } => capture_pattern_node::print(node),
        Node::CaseMatchNode { .. } => case_match_node::print(node),
        Node::CaseNode { .. } => case_node::print(node),
        Node::ClassNode { .. } => class_node::print(node),
        Node::ClassVariableAndWriteNode { .. } => class_variable_and_write_node::print(node),
        Node::ClassVariableOperatorWriteNode { .. } => {
            class_variable_operator_write_node::print(node)
        }
        Node::ClassVariableOrWriteNode { .. } => class_variable_or_write_node::print(node),
        Node::ClassVariableReadNode { .. } => class_variable_read_node::print(node),
        Node::ClassVariableTargetNode { .. } => class_variable_target_node::print(node),
        Node::ClassVariableWriteNode { .. } => class_variable_write_node::print(node),
        Node::ConstantAndWriteNode { .. } => constant_and_write_node::print(node),
        Node::ConstantOperatorWriteNode { .. } => constant_operator_write_node::print(node),
        Node::ConstantOrWriteNode { .. } => constant_or_write_node::print(node),
        Node::ConstantPathAndWriteNode { .. } => constant_path_and_write_node::print(node),
        Node::ConstantPathNode { .. } => constant_path_node::print(node),
        Node::ConstantPathOperatorWriteNode { .. } => {
            constant_path_operator_write_node::print(node)
        }
        Node::ConstantPathOrWriteNode { .. } => constant_path_or_write_node::print(node),
        Node::ConstantPathTargetNode { .. } => constant_path_target_node::print(node),
        Node::ConstantPathWriteNode { .. } => constant_path_write_node::print(node),
        Node::ConstantReadNode { .. } => constant_read_node::print(node),
        Node::ConstantTargetNode { .. } => constant_target_node::print(node),
        Node::ConstantWriteNode { .. } => constant_write_node::print(node),
        Node::DefNode { .. } => def_node::print(node),
        Node::DefinedNode { .. } => defined_node::print(node),
        Node::ElseNode { .. } => else_node::print(node),
        Node::EmbeddedStatementsNode { .. } => embedded_statements_node::print(node),
        Node::EmbeddedVariableNode { .. } => embedded_variable_node::print(node),
        Node::EnsureNode { .. } => ensure_node::print(node),
        Node::FalseNode { .. } => false_node::print(node),
        Node::FindPatternNode { .. } => find_pattern_node::print(node),
        Node::FlipFlopNode { .. } => flip_flop_node::print(node),
        Node::FloatNode { .. } => float_node::print(node),
        Node::ForNode { .. } => for_node::print(node),
        Node::ForwardingArgumentsNode { .. } => forwarding_arguments_node::print(node),
        Node::ForwardingParameterNode { .. } => forwarding_parameter_node::print(node),
        Node::ForwardingSuperNode { .. } => forwarding_super_node::print(node),
        Node::GlobalVariableAndWriteNode { .. } => global_variable_and_write_node::print(node),
        Node::GlobalVariableOperatorWriteNode { .. } => {
            global_variable_operator_write_node::print(node)
        }
        Node::GlobalVariableOrWriteNode { .. } => global_variable_or_write_node::print(node),
        Node::GlobalVariableReadNode { .. } => global_variable_read_node::print(node),
        Node::GlobalVariableTargetNode { .. } => global_variable_target_node::print(node),
        Node::GlobalVariableWriteNode { .. } => global_variable_write_node::print(node),
        Node::HashNode { .. } => hash_node::print(node),
        Node::HashPatternNode { .. } => hash_pattern_node::print(node),
        Node::IfNode { .. } => if_node::print(node),
        Node::ImaginaryNode { .. } => imaginary_node::print(node),
        Node::ImplicitNode { .. } => implicit_node::print(node),
        Node::ImplicitRestNode { .. } => implicit_rest_node::print(node),
        Node::InNode { .. } => in_node::print(node),
        Node::IndexAndWriteNode { .. } => index_and_write_node::print(node),
        Node::IndexOperatorWriteNode { .. } => index_operator_write_node::print(node),
        Node::IndexOrWriteNode { .. } => index_or_write_node::print(node),
        Node::IndexTargetNode { .. } => index_target_node::print(node),
        Node::InstanceVariableAndWriteNode { .. } => instance_variable_and_write_node::print(node),
        Node::InstanceVariableOperatorWriteNode { .. } => {
            instance_variable_operator_write_node::print(node)
        }
        Node::InstanceVariableOrWriteNode { .. } => instance_variable_or_write_node::print(node),
        Node::InstanceVariableReadNode { .. } => instance_variable_read_node::print(node),
        Node::InstanceVariableTargetNode { .. } => instance_variable_target_node::print(node),
        Node::InstanceVariableWriteNode { .. } => instance_variable_write_node::print(node),
        Node::IntegerNode { .. } => integer_node::print(node),
        Node::InterpolatedMatchLastLineNode { .. } => {
            interpolated_match_last_line_node::print(node)
        }
        Node::InterpolatedRegularExpressionNode { .. } => {
            interpolated_regular_expression_node::print(node)
        }
        Node::InterpolatedStringNode { .. } => interpolated_string_node::print(node),
        Node::InterpolatedSymbolNode { .. } => interpolated_symbol_node::print(node),
        Node::InterpolatedXStringNode { .. } => interpolated_x_string_node::print(node),
        Node::ItLocalVariableReadNode { .. } => it_local_variable_read_node::print(node),
        Node::ItParametersNode { .. } => it_parameters_node::print(node),
        Node::KeywordHashNode { .. } => keyword_hash_node::print(node),
        Node::KeywordRestParameterNode { .. } => keyword_rest_parameter_node::print(node),
        Node::LambdaNode { .. } => lambda_node::print(node),
        Node::LocalVariableAndWriteNode { .. } => local_variable_and_write_node::print(node),
        Node::LocalVariableOperatorWriteNode { .. } => {
            local_variable_operator_write_node::print(node)
        }
        Node::LocalVariableOrWriteNode { .. } => local_variable_or_write_node::print(node),
        Node::LocalVariableReadNode { .. } => local_variable_read_node::print(node),
        Node::LocalVariableTargetNode { .. } => local_variable_target_node::print(node),
        Node::LocalVariableWriteNode { .. } => local_variable_write_node::print(node),
        Node::MatchLastLineNode { .. } => match_last_line_node::print(node),
        Node::MatchPredicateNode { .. } => match_predicate_node::print(node),
        Node::MatchRequiredNode { .. } => match_required_node::print(node),
        Node::MatchWriteNode { .. } => match_write_node::print(node),
        Node::MissingNode { .. } => missing_node::print(node),
        Node::ModuleNode { .. } => module_node::print(node),
        Node::MultiTargetNode { .. } => multi_target_node::print(node),
        Node::MultiWriteNode { .. } => multi_write_node::print(node),
        Node::NextNode { .. } => next_node::print(node),
        Node::NilNode { .. } => nil_node::print(node),
        Node::NoKeywordsParameterNode { .. } => no_keywords_parameter_node::print(node),
        Node::NumberedParametersNode { .. } => numbered_parameters_node::print(node),
        Node::NumberedReferenceReadNode { .. } => numbered_reference_read_node::print(node),
        Node::OptionalKeywordParameterNode { .. } => optional_keyword_parameter_node::print(node),
        Node::OptionalParameterNode { .. } => optional_parameter_node::print(node),
        Node::OrNode { .. } => or_node::print(node),
        Node::ParametersNode { .. } => parameters_node::print(node),
        Node::ParenthesesNode { .. } => parentheses_node::print(node),
        Node::PinnedExpressionNode { .. } => pinned_expression_node::print(node),
        Node::PinnedVariableNode { .. } => pinned_variable_node::print(node),
        Node::PostExecutionNode { .. } => post_execution_node::print(node),
        Node::PreExecutionNode { .. } => pre_execution_node::print(node),
        Node::ProgramNode { .. } => program_node::print(node),
        Node::RangeNode { .. } => range_node::print(node),
        Node::RationalNode { .. } => rational_node::print(node),
        Node::RedoNode { .. } => redo_node::print(node),
        Node::RegularExpressionNode { .. } => regular_expression_node::print(node),
        Node::RequiredKeywordParameterNode { .. } => required_keyword_parameter_node::print(node),
        Node::RequiredParameterNode { .. } => required_parameter_node::print(node),
        Node::RescueModifierNode { .. } => rescue_modifier_node::print(node),
        Node::RescueNode { .. } => rescue_node::print(node),
        Node::RestParameterNode { .. } => rest_parameter_node::print(node),
        Node::RetryNode { .. } => retry_node::print(node),
        Node::ReturnNode { .. } => return_node::print(node),
        Node::SelfNode { .. } => self_node::print(node),
        Node::ShareableConstantNode { .. } => shareable_constant_node::print(node),
        Node::SingletonClassNode { .. } => singleton_class_node::print(node),
        Node::SourceEncodingNode { .. } => source_encoding_node::print(node),
        Node::SourceFileNode { .. } => source_file_node::print(node),
        Node::SourceLineNode { .. } => source_line_node::print(node),
        Node::SplatNode { .. } => splat_node::print(node),
        Node::StatementsNode { .. } => statements_node::print(node),
        Node::StringNode { .. } => string_node::print(node),
        Node::SuperNode { .. } => super_node::print(node),
        Node::SymbolNode { .. } => symbol_node::print(node),
        Node::TrueNode { .. } => true_node::print(node),
        Node::UndefNode { .. } => undef_node::print(node),
        Node::UnlessNode { .. } => unless_node::print(node),
        Node::UntilNode { .. } => until_node::print(node),
        Node::WhenNode { .. } => when_node::print(node),
        Node::WhileNode { .. } => while_node::print(node),
        Node::XStringNode { .. } => x_string_node::print(node),
        Node::YieldNode { .. } => yield_node::print(node),
    }
}
