use crate::Document;
use crate::builder::prism::BuildContext;
use crate::builder::prism::build_main::build_main;
use crate::builder::prism::build_node_variant::*;
use crate::builder::prism::comments::Target;
use ruby_prism::Node;
use std::marker::PhantomData;

/// Internal function to build a node with optional content
#[rustfmt::skip]
fn _node_builder<T>(node: &Node<'_>, ctx: &mut BuildContext, _: PhantomData<T>) -> Option<Document> {
    // ** SAVE PREVIOUS MAX BLANK LINES **
    let prev_max_blank_lines = ctx.max_blank_lines;
    // ** SET MAX BLANK LINES FOR NODE TYPE **
    ctx.max_blank_lines = match node {
        Node::ProgramNode { .. } => 1,
        Node::StatementsNode { .. } => 1,
        _ => 0,
    };
    // ** BUILD NODE BASED ON TYPE **
    let node_doc = match node {
        Node::AliasGlobalVariableNode           { .. } => alias_global_variable_node::build_alias_global_variable_node                      (&node.as_alias_global_variable_node().unwrap()           , ctx),
        Node::AliasMethodNode                   { .. } => alias_method_node::build_alias_method_node                                        (&node.as_alias_method_node().unwrap()                    , ctx),
        Node::AlternationPatternNode            { .. } => alternation_pattern_node::build_alternation_pattern_node                          (&node.as_alternation_pattern_node().unwrap()             , ctx),
        Node::AndNode                           { .. } => and_node::build_and_node                                                          (&node.as_and_node().unwrap()                             , ctx),
        Node::ArgumentsNode                     { .. } => arguments_node::build_arguments_node                                              (&node.as_arguments_node().unwrap()                       , ctx),
        Node::ArrayNode                         { .. } => array_node::build_array_node                                                      (&node.as_array_node().unwrap()                           , ctx),
        Node::ArrayPatternNode                  { .. } => array_pattern_node::build_array_pattern_node                                      (&node.as_array_pattern_node().unwrap()                   , ctx),
        Node::AssocNode                         { .. } => assoc_node::build_assoc_node                                                      (&node.as_assoc_node().unwrap()                           , ctx),
        Node::AssocSplatNode                    { .. } => assoc_splat_node::build_assoc_splat_node                                          (&node.as_assoc_splat_node().unwrap()                     , ctx),
        Node::BackReferenceReadNode             { .. } => back_reference_read_node::build_back_reference_read_node                          (&node.as_back_reference_read_node().unwrap()             , ctx),
        Node::BeginNode                         { .. } => begin_node::build_begin_node                                                      (&node.as_begin_node().unwrap()                           , ctx),
        Node::BlockArgumentNode                 { .. } => block_argument_node::build_block_argument_node                                    (&node.as_block_argument_node().unwrap()                  , ctx),
        Node::BlockLocalVariableNode            { .. } => block_local_variable_node::build_block_local_variable_node                        (&node.as_block_local_variable_node().unwrap()            , ctx),
        Node::BlockNode                         { .. } => block_node::build_block_node                                                      (&node.as_block_node().unwrap()                           , ctx),
        Node::BlockParameterNode                { .. } => block_parameter_node::build_block_parameter_node                                  (&node.as_block_parameter_node().unwrap()                 , ctx),
        Node::BlockParametersNode               { .. } => block_parameters_node::build_block_parameters_node                                (&node.as_block_parameters_node().unwrap()                , ctx),
        Node::BreakNode                         { .. } => break_node::build_break_node                                                      (&node.as_break_node().unwrap()                           , ctx),
        Node::CallAndWriteNode                  { .. } => call_and_write_node::build_call_and_write_node                                    (&node.as_call_and_write_node().unwrap()                  , ctx),
        Node::CallNode                          { .. } => call_node::build_call_node                                                        (&node.as_call_node().unwrap()                            , ctx),
        Node::CallOperatorWriteNode             { .. } => call_operator_write_node::build_call_operator_write_node                          (&node.as_call_operator_write_node().unwrap()             , ctx),
        Node::CallOrWriteNode                   { .. } => call_or_write_node::build_call_or_write_node                                      (&node.as_call_or_write_node().unwrap()                   , ctx),
        Node::CallTargetNode                    { .. } => call_target_node::build_call_target_node                                          (&node.as_call_target_node().unwrap()                     , ctx),
        Node::CapturePatternNode                { .. } => capture_pattern_node::build_capture_pattern_node                                  (&node.as_capture_pattern_node().unwrap()                 , ctx),
        Node::CaseMatchNode                     { .. } => case_match_node::build_case_match_node                                            (&node.as_case_match_node().unwrap()                      , ctx),
        Node::CaseNode                          { .. } => case_node::build_case_node                                                        (&node.as_case_node().unwrap()                            , ctx),
        Node::ClassNode                         { .. } => class_node::build_class_node                                                      (&node.as_class_node().unwrap()                           , ctx),
        Node::ClassVariableAndWriteNode         { .. } => class_variable_and_write_node::build_class_variable_and_write_node                (&node.as_class_variable_and_write_node().unwrap()        , ctx),
        Node::ClassVariableOperatorWriteNode    { .. } => class_variable_operator_write_node::build_class_variable_operator_write_node      (&node.as_class_variable_operator_write_node().unwrap()   , ctx),
        Node::ClassVariableOrWriteNode          { .. } => class_variable_or_write_node::build_class_variable_or_write_node                  (&node.as_class_variable_or_write_node().unwrap()         , ctx),
        Node::ClassVariableReadNode             { .. } => class_variable_read_node::build_class_variable_read_node                          (&node.as_class_variable_read_node().unwrap()             , ctx),
        Node::ClassVariableTargetNode           { .. } => class_variable_target_node::build_class_variable_target_node                      (&node.as_class_variable_target_node().unwrap()           , ctx),
        Node::ClassVariableWriteNode            { .. } => class_variable_write_node::build_class_variable_write_node                        (&node.as_class_variable_write_node().unwrap()            , ctx),
        Node::ConstantAndWriteNode              { .. } => constant_and_write_node::build_constant_and_write_node                            (&node.as_constant_and_write_node().unwrap()              , ctx),
        Node::ConstantOperatorWriteNode         { .. } => constant_operator_write_node::build_constant_operator_write_node                  (&node.as_constant_operator_write_node().unwrap()         , ctx),
        Node::ConstantOrWriteNode               { .. } => constant_or_write_node::build_constant_or_write_node                              (&node.as_constant_or_write_node().unwrap()               , ctx),
        Node::ConstantPathAndWriteNode          { .. } => constant_path_and_write_node::build_constant_path_and_write_node                  (&node.as_constant_path_and_write_node().unwrap()         , ctx),
        Node::ConstantPathNode                  { .. } => constant_path_node::build_constant_path_node                                      (&node.as_constant_path_node().unwrap()                   , ctx),
        Node::ConstantPathOperatorWriteNode     { .. } => constant_path_operator_write_node::build_constant_path_operator_write_node        (&node.as_constant_path_operator_write_node().unwrap()    , ctx),
        Node::ConstantPathOrWriteNode           { .. } => constant_path_or_write_node::build_constant_path_or_write_node                    (&node.as_constant_path_or_write_node().unwrap()          , ctx),
        Node::ConstantPathTargetNode            { .. } => constant_path_target_node::build_constant_path_target_node                        (&node.as_constant_path_target_node().unwrap()            , ctx),
        Node::ConstantPathWriteNode             { .. } => constant_path_write_node::build_constant_path_write_node                          (&node.as_constant_path_write_node().unwrap()             , ctx),
        Node::ConstantReadNode                  { .. } => constant_read_node::build_constant_read_node                                      (&node.as_constant_read_node().unwrap()                   , ctx),
        Node::ConstantTargetNode                { .. } => constant_target_node::build_constant_target_node                                  (&node.as_constant_target_node().unwrap()                 , ctx),
        Node::ConstantWriteNode                 { .. } => constant_write_node::build_constant_write_node                                    (&node.as_constant_write_node().unwrap()                  , ctx),
        Node::DefNode                           { .. } => def_node::build_def_node                                                          (&node.as_def_node().unwrap()                             , ctx),
        Node::DefinedNode                       { .. } => defined_node::build_defined_node                                                  (&node.as_defined_node().unwrap()                         , ctx),
        Node::ElseNode                          { .. } => else_node::build_else_node                                                        (&node.as_else_node().unwrap()                            , ctx),
        Node::EmbeddedStatementsNode            { .. } => embedded_statements_node::build_embedded_statements_node                          (&node.as_embedded_statements_node().unwrap()             , ctx),
        Node::EmbeddedVariableNode              { .. } => embedded_variable_node::build_embedded_variable_node                              (&node.as_embedded_variable_node().unwrap()               , ctx),
        Node::EnsureNode                        { .. } => ensure_node::build_ensure_node                                                    (&node.as_ensure_node().unwrap()                          , ctx),
        Node::FalseNode                         { .. } => false_node::build_false_node                                                      (&node.as_false_node().unwrap()                           , ctx),
        Node::FindPatternNode                   { .. } => find_pattern_node::build_find_pattern_node                                        (&node.as_find_pattern_node().unwrap()                    , ctx),
        Node::FlipFlopNode                      { .. } => flip_flop_node::build_flip_flop_node                                              (&node.as_flip_flop_node().unwrap()                       , ctx),
        Node::FloatNode                         { .. } => float_node::build_float_node                                                      (&node.as_float_node().unwrap()                           , ctx),
        Node::ForNode                           { .. } => for_node::build_for_node                                                          (&node.as_for_node().unwrap()                             , ctx),
        Node::ForwardingArgumentsNode           { .. } => forwarding_arguments_node::build_forwarding_arguments_node                        (&node.as_forwarding_arguments_node().unwrap()            , ctx),
        Node::ForwardingParameterNode           { .. } => forwarding_parameter_node::build_forwarding_parameter_node                        (&node.as_forwarding_parameter_node().unwrap()            , ctx),
        Node::ForwardingSuperNode               { .. } => forwarding_super_node::build_forwarding_super_node                                (&node.as_forwarding_super_node().unwrap()                , ctx),
        Node::GlobalVariableAndWriteNode        { .. } => global_variable_and_write_node::build_global_variable_and_write_node              (&node.as_global_variable_and_write_node().unwrap()       , ctx),
        Node::GlobalVariableOperatorWriteNode   { .. } => global_variable_operator_write_node::build_global_variable_operator_write_node    (&node.as_global_variable_operator_write_node().unwrap()  , ctx),
        Node::GlobalVariableOrWriteNode         { .. } => global_variable_or_write_node::build_global_variable_or_write_node                (&node.as_global_variable_or_write_node().unwrap()        , ctx),
        Node::GlobalVariableReadNode            { .. } => global_variable_read_node::build_global_variable_read_node                        (&node.as_global_variable_read_node().unwrap()            , ctx),
        Node::GlobalVariableTargetNode          { .. } => global_variable_target_node::build_global_variable_target_node                    (&node.as_global_variable_target_node().unwrap()          , ctx),
        Node::GlobalVariableWriteNode           { .. } => global_variable_write_node::build_global_variable_write_node                      (&node.as_global_variable_write_node().unwrap()           , ctx),
        Node::HashNode                          { .. } => hash_node::build_hash_node                                                        (&node.as_hash_node().unwrap()                            , ctx),
        Node::HashPatternNode                   { .. } => hash_pattern_node::build_hash_pattern_node                                        (&node.as_hash_pattern_node().unwrap()                    , ctx),
        Node::IfNode                            { .. } => if_node::build_if_node                                                            (&node.as_if_node().unwrap()                              , ctx),
        Node::ImaginaryNode                     { .. } => imaginary_node::build_imaginary_node                                              (&node.as_imaginary_node().unwrap()                       , ctx),
        Node::ImplicitNode                      { .. } => implicit_node::build_implicit_node                                                (&node.as_implicit_node().unwrap()                        , ctx),
        Node::ImplicitRestNode                  { .. } => implicit_rest_node::build_implicit_rest_node                                      (&node.as_implicit_rest_node().unwrap()                   , ctx),
        Node::InNode                            { .. } => in_node::build_in_node                                                            (&node.as_in_node().unwrap()                              , ctx),
        Node::IndexAndWriteNode                 { .. } => index_and_write_node::build_index_and_write_node                                  (&node.as_index_and_write_node().unwrap()                 , ctx),
        Node::IndexOperatorWriteNode            { .. } => index_operator_write_node::build_index_operator_write_node                        (&node.as_index_operator_write_node().unwrap()            , ctx),
        Node::IndexOrWriteNode                  { .. } => index_or_write_node::build_index_or_write_node                                    (&node.as_index_or_write_node().unwrap()                  , ctx),
        Node::IndexTargetNode                   { .. } => index_target_node::build_index_target_node                                        (&node.as_index_target_node().unwrap()                    , ctx),
        Node::InstanceVariableAndWriteNode      { .. } => instance_variable_and_write_node::build_instance_variable_and_write_node          (&node.as_instance_variable_and_write_node().unwrap()     , ctx),
        Node::InstanceVariableOperatorWriteNode { .. } => instance_variable_operator_write_node::build_instance_variable_operator_write_node(&node.as_instance_variable_operator_write_node().unwrap(), ctx),
        Node::InstanceVariableOrWriteNode       { .. } => instance_variable_or_write_node::build_instance_variable_or_write_node            (&node.as_instance_variable_or_write_node().unwrap()      , ctx),
        Node::InstanceVariableReadNode          { .. } => instance_variable_read_node::build_instance_variable_read_node                    (&node.as_instance_variable_read_node().unwrap()          , ctx),
        Node::InstanceVariableTargetNode        { .. } => instance_variable_target_node::build_instance_variable_target_node                (&node.as_instance_variable_target_node().unwrap()        , ctx),
        Node::InstanceVariableWriteNode         { .. } => instance_variable_write_node::build_instance_variable_write_node                  (&node.as_instance_variable_write_node().unwrap()         , ctx),
        Node::IntegerNode                       { .. } => integer_node::build_integer_node                                                  (&node.as_integer_node().unwrap()                         , ctx),
        Node::InterpolatedMatchLastLineNode     { .. } => interpolated_match_last_line_node::build_interpolated_match_last_line_node        (&node.as_interpolated_match_last_line_node().unwrap()    , ctx),
        Node::InterpolatedRegularExpressionNode { .. } => interpolated_regular_expression_node::build_interpolated_regular_expression_node  (&node.as_interpolated_regular_expression_node().unwrap() , ctx),
        Node::InterpolatedStringNode            { .. } => interpolated_string_node::build_interpolated_string_node                          (&node.as_interpolated_string_node().unwrap()             , ctx),
        Node::InterpolatedSymbolNode            { .. } => interpolated_symbol_node::build_interpolated_symbol_node                          (&node.as_interpolated_symbol_node().unwrap()             , ctx),
        Node::InterpolatedXStringNode           { .. } => interpolated_x_string_node::build_interpolated_x_string_node                      (&node.as_interpolated_x_string_node().unwrap()           , ctx),
        Node::ItLocalVariableReadNode           { .. } => it_local_variable_read_node::build_it_local_variable_read_node                    (&node.as_it_local_variable_read_node().unwrap()          , ctx),
        Node::ItParametersNode                  { .. } => it_parameters_node::build_it_parameters_node                                      (&node.as_it_parameters_node().unwrap()                   , ctx),
        Node::KeywordHashNode                   { .. } => keyword_hash_node::build_keyword_hash_node                                        (&node.as_keyword_hash_node().unwrap()                    , ctx),
        Node::KeywordRestParameterNode          { .. } => keyword_rest_parameter_node::build_keyword_rest_parameter_node                    (&node.as_keyword_rest_parameter_node().unwrap()          , ctx),
        Node::LambdaNode                        { .. } => lambda_node::build_lambda_node                                                    (&node.as_lambda_node().unwrap()                          , ctx),
        Node::LocalVariableAndWriteNode         { .. } => local_variable_and_write_node::build_local_variable_and_write_node                (&node.as_local_variable_and_write_node().unwrap()        , ctx),
        Node::LocalVariableOperatorWriteNode    { .. } => local_variable_operator_write_node::build_local_variable_operator_write_node      (&node.as_local_variable_operator_write_node().unwrap()   , ctx),
        Node::LocalVariableOrWriteNode          { .. } => local_variable_or_write_node::build_local_variable_or_write_node                  (&node.as_local_variable_or_write_node().unwrap()         , ctx),
        Node::LocalVariableReadNode             { .. } => local_variable_read_node::build_local_variable_read_node                          (&node.as_local_variable_read_node().unwrap()             , ctx),
        Node::LocalVariableTargetNode           { .. } => local_variable_target_node::build_local_variable_target_node                      (&node.as_local_variable_target_node().unwrap()           , ctx),
        Node::LocalVariableWriteNode            { .. } => local_variable_write_node::build_local_variable_write_node                        (&node.as_local_variable_write_node().unwrap()            , ctx),
        Node::MatchLastLineNode                 { .. } => match_last_line_node::build_match_last_line_node                                  (&node.as_match_last_line_node().unwrap()                 , ctx),
        Node::MatchPredicateNode                { .. } => match_predicate_node::build_match_predicate_node                                  (&node.as_match_predicate_node().unwrap()                 , ctx),
        Node::MatchRequiredNode                 { .. } => match_required_node::build_match_required_node                                    (&node.as_match_required_node().unwrap()                  , ctx),
        Node::MatchWriteNode                    { .. } => match_write_node::build_match_write_node                                          (&node.as_match_write_node().unwrap()                     , ctx),
        Node::MissingNode                       { .. } => missing_node::build_missing_node                                                  (&node.as_missing_node().unwrap()                         , ctx),
        Node::ModuleNode                        { .. } => module_node::build_module_node                                                    (&node.as_module_node().unwrap()                          , ctx),
        Node::MultiTargetNode                   { .. } => multi_target_node::build_multi_target_node                                        (&node.as_multi_target_node().unwrap()                    , ctx),
        Node::MultiWriteNode                    { .. } => multi_write_node::build_multi_write_node                                          (&node.as_multi_write_node().unwrap()                     , ctx),
        Node::NextNode                          { .. } => next_node::build_next_node                                                        (&node.as_next_node().unwrap()                            , ctx),
        Node::NilNode                           { .. } => nil_node::build_nil_node                                                          (&node.as_nil_node().unwrap()                             , ctx),
        Node::NoKeywordsParameterNode           { .. } => no_keywords_parameter_node::build_no_keywords_parameter_node                      (&node.as_no_keywords_parameter_node().unwrap()           , ctx),
        Node::NumberedParametersNode            { .. } => numbered_parameters_node::build_numbered_parameters_node                          (&node.as_numbered_parameters_node().unwrap()             , ctx),
        Node::NumberedReferenceReadNode         { .. } => numbered_reference_read_node::build_numbered_reference_read_node                  (&node.as_numbered_reference_read_node().unwrap()         , ctx),
        Node::OptionalKeywordParameterNode      { .. } => optional_keyword_parameter_node::build_optional_keyword_parameter_node            (&node.as_optional_keyword_parameter_node().unwrap()      , ctx),
        Node::OptionalParameterNode             { .. } => optional_parameter_node::build_optional_parameter_node                            (&node.as_optional_parameter_node().unwrap()              , ctx),
        Node::OrNode                            { .. } => or_node::build_or_node                                                            (&node.as_or_node().unwrap()                              , ctx),
        Node::ParametersNode                    { .. } => parameters_node::build_parameters_node                                            (&node.as_parameters_node().unwrap()                      , ctx),
        Node::ParenthesesNode                   { .. } => parentheses_node::build_parentheses_node                                          (&node.as_parentheses_node().unwrap()                     , ctx),
        Node::PinnedExpressionNode              { .. } => pinned_expression_node::build_pinned_expression_node                              (&node.as_pinned_expression_node().unwrap()               , ctx),
        Node::PinnedVariableNode                { .. } => pinned_variable_node::build_pinned_variable_node                                  (&node.as_pinned_variable_node().unwrap()                 , ctx),
        Node::PostExecutionNode                 { .. } => post_execution_node::build_post_execution_node                                    (&node.as_post_execution_node().unwrap()                  , ctx),
        Node::PreExecutionNode                  { .. } => pre_execution_node::build_pre_execution_node                                      (&node.as_pre_execution_node().unwrap()                   , ctx),
        Node::ProgramNode                       { .. } => program_node::build_program_node                                                  (&node.as_program_node().unwrap()                         , ctx),
        Node::RangeNode                         { .. } => range_node::build_range_node                                                      (&node.as_range_node().unwrap()                           , ctx),
        Node::RationalNode                      { .. } => rational_node::build_rational_node                                                (&node.as_rational_node().unwrap()                        , ctx),
        Node::RedoNode                          { .. } => redo_node::build_redo_node                                                        (&node.as_redo_node().unwrap()                            , ctx),
        Node::RegularExpressionNode             { .. } => regular_expression_node::build_regular_expression_node                            (&node.as_regular_expression_node().unwrap()              , ctx),
        Node::RequiredKeywordParameterNode      { .. } => required_keyword_parameter_node::build_required_keyword_parameter_node            (&node.as_required_keyword_parameter_node().unwrap()      , ctx),
        Node::RequiredParameterNode             { .. } => required_parameter_node::build_required_parameter_node                            (&node.as_required_parameter_node().unwrap()              , ctx),
        Node::RescueModifierNode                { .. } => rescue_modifier_node::build_rescue_modifier_node                                  (&node.as_rescue_modifier_node().unwrap()                 , ctx),
        Node::RescueNode                        { .. } => rescue_node::build_rescue_node                                                    (&node.as_rescue_node().unwrap()                          , ctx),
        Node::RestParameterNode                 { .. } => rest_parameter_node::build_rest_parameter_node                                    (&node.as_rest_parameter_node().unwrap()                  , ctx),
        Node::RetryNode                         { .. } => retry_node::build_retry_node                                                      (&node.as_retry_node().unwrap()                           , ctx),
        Node::ReturnNode                        { .. } => return_node::build_return_node                                                    (&node.as_return_node().unwrap()                          , ctx),
        Node::SelfNode                          { .. } => self_node::build_self_node                                                        (&node.as_self_node().unwrap()                            , ctx),
        Node::ShareableConstantNode             { .. } => shareable_constant_node::build_shareable_constant_node                            (&node.as_shareable_constant_node().unwrap()              , ctx),
        Node::SingletonClassNode                { .. } => singleton_class_node::build_singleton_class_node                                  (&node.as_singleton_class_node().unwrap()                 , ctx),
        Node::SourceEncodingNode                { .. } => source_encoding_node::build_source_encoding_node                                  (&node.as_source_encoding_node().unwrap()                 , ctx),
        Node::SourceFileNode                    { .. } => source_file_node::build_source_file_node                                          (&node.as_source_file_node().unwrap()                     , ctx),
        Node::SourceLineNode                    { .. } => source_line_node::build_source_line_node                                          (&node.as_source_line_node().unwrap()                     , ctx),
        Node::SplatNode                         { .. } => splat_node::build_splat_node                                                      (&node.as_splat_node().unwrap()                           , ctx),
        Node::StatementsNode                    { .. } => statements_node::build_statements_node                                            (&node.as_statements_node().unwrap()                      , ctx),
        Node::StringNode                        { .. } => string_node::build_string_node                                                    (&node.as_string_node().unwrap()                          , ctx),
        Node::SuperNode                         { .. } => super_node::build_super_node                                                      (&node.as_super_node().unwrap()                           , ctx),
        Node::SymbolNode                        { .. } => symbol_node::build_symbol_node                                                    (&node.as_symbol_node().unwrap()                          , ctx),
        Node::TrueNode                          { .. } => true_node::build_true_node                                                        (&node.as_true_node().unwrap()                            , ctx),
        Node::UndefNode                         { .. } => undef_node::build_undef_node                                                      (&node.as_undef_node().unwrap()                           , ctx),
        Node::UnlessNode                        { .. } => unless_node::build_unless_node                                                    (&node.as_unless_node().unwrap()                          , ctx),
        Node::UntilNode                         { .. } => until_node::build_until_node                                                      (&node.as_until_node().unwrap()                           , ctx),
        Node::WhenNode                          { .. } => when_node::build_when_node                                                        (&node.as_when_node().unwrap()                            , ctx),
        Node::WhileNode                         { .. } => while_node::build_while_node                                                      (&node.as_while_node().unwrap()                           , ctx),
        Node::XStringNode                       { .. } => x_string_node::build_x_string_node                                                (&node.as_x_string_node().unwrap()                        , ctx),
        Node::YieldNode                         { .. } => yield_node::build_yield_node                                                      (&node.as_yield_node().unwrap()                           , ctx),
    };
    // ** RESTORE PREVIOUS MAX BLANK LINES **
    ctx.max_blank_lines = prev_max_blank_lines;
    node_doc
}

/// Build a node into a Document
pub fn build_node<'sh>(node: &Node<'_>, ctx: &mut BuildContext) -> Option<Document> {
    build_main(_node_builder, node, PhantomData::<()>, ctx, &Target::from_node(node))
}
